"""empty message

Revision ID: 1863f087d8d9
Revises: eb01f659c1f6
Create Date: 2024-06-19 22:14:14.553754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1863f087d8d9'
down_revision = 'eb01f659c1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_constraint('Product_product_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.create_unique_constraint('Product_product_code_key', ['product_code'])

    # ### end Alembic commands ###
