"""empty message

Revision ID: 1889e74cbbc9
Revises: 8d8b181a3248
Create Date: 2024-06-19 20:58:21.890100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1889e74cbbc9'
down_revision = '8d8b181a3248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('product_name')
        batch_op.drop_column('product_quantity')
        batch_op.drop_column('product_id')
        batch_op.drop_column('product_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_product_id_fkey', 'Product', ['product_id'], ['id'])

    op.drop_table('order_items')
    # ### end Alembic commands ###
