"""empty message

Revision ID: 500b31b07c8e
Revises: e6cec6a073bf
Create Date: 2024-05-09 12:37:23.418692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500b31b07c8e'
down_revision = 'e6cec6a073bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MerchantUser',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=1000), nullable=True),
    sa.Column('lastname', sa.String(length=1000), nullable=True),
    sa.Column('company_name', sa.String(length=1000), nullable=True),
    sa.Column('company_emailaddress', sa.String(length=500), nullable=True),
    sa.Column('company_address', sa.String(length=500), nullable=True),
    sa.Column('company_mobile', sa.String(length=30), nullable=True),
    sa.Column('company_postcode', sa.String(length=500), nullable=True),
    sa.Column('company_registrationno', sa.String(length=500), nullable=True),
    sa.Column('company_password_hash', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.drop_table('merchant_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_user',
    sa.Column('company_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('company_emailaddress', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('company_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('company_mobile', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('company_postcode', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('company_registrationno', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('company_id', name='merchant_user_pkey')
    )
    op.drop_table('MerchantUser')
    # ### end Alembic commands ###
