"""empty message

Revision ID: 8d8b181a3248
Revises: 6e996a25167d
Create Date: 2024-06-19 20:47:13.365047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d8b181a3248'
down_revision = '6e996a25167d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_first_name', sa.String(), nullable=False),
    sa.Column('user_last_name', sa.String(), nullable=False),
    sa.Column('user_email_address', sa.String(), nullable=False),
    sa.Column('user_mobile', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('shipping_address', sa.String(), nullable=False),
    sa.Column('shipping_city', sa.String(), nullable=False),
    sa.Column('shipping_state', sa.String(), nullable=False),
    sa.Column('shipping_zip', sa.String(), nullable=False),
    sa.Column('shipping_country', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('payment',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.drop_table('payment_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_record',
    sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_mobile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shipping_city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shipping_state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shipping_zip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shipping_country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], name='payment_record_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='payment_record_user_id_fkey'),
    sa.PrimaryKeyConstraint('transaction_id', name='payment_record_pkey')
    )
    op.drop_table('payment')
    op.drop_table('orders')
    # ### end Alembic commands ###
