"""empty message

Revision ID: 948aa597cb44
Revises: aa4ebae969ed
Create Date: 2024-06-16 23:44:40.851472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948aa597cb44'
down_revision = 'aa4ebae969ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_record',
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('mobile_no', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('product_price')
        batch_op.drop_column('total_price')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    op.drop_table('payment_record')
    # ### end Alembic commands ###
