"""empty message

Revision ID: ae04ffe4d0ab
Revises: 1889e74cbbc9
Create Date: 2024-06-19 21:14:17.047381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae04ffe4d0ab'
down_revision = '1889e74cbbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['product_code'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email_address'])
        batch_op.create_unique_constraint(None, ['mobile'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
