"""empty message

Revision ID: ae8445eb3dfc
Revises: 500b31b07c8e
Create Date: 2024-05-09 13:43:20.879893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8445eb3dfc'
down_revision = '500b31b07c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_category_name', sa.String(length=255), nullable=False),
    sa.Column('product_category_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_category_code'),
    sa.UniqueConstraint('product_category_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_category')
    # ### end Alembic commands ###
