"""empty message

Revision ID: e6cec6a073bf
Revises: 69679156fbfd
Create Date: 2024-05-09 04:44:13.533842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cec6a073bf'
down_revision = '69679156fbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_user',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=1000), nullable=True),
    sa.Column('lastname', sa.String(length=1000), nullable=True),
    sa.Column('company_name', sa.String(length=1000), nullable=True),
    sa.Column('company_emailaddress', sa.String(length=500), nullable=True),
    sa.Column('company_address', sa.String(length=500), nullable=True),
    sa.Column('company_mobile', sa.String(length=30), nullable=True),
    sa.Column('company_postcode', sa.String(length=500), nullable=True),
    sa.Column('company_registrationno', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_user')
    # ### end Alembic commands ###
