"""empty message

Revision ID: eb01f659c1f6
Revises: ae04ffe4d0ab
Create Date: 2024-06-19 22:05:10.095979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb01f659c1f6'
down_revision = 'ae04ffe4d0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_constraint('user_email_address_key', type_='unique')
        batch_op.drop_constraint('user_mobile_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_mobile_key', ['mobile'])
        batch_op.create_unique_constraint('user_email_address_key', ['email_address'])
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
